# Generated by Django 5.0.7 on 2024-07-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_snippet_priv_alter_snippet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='is_public',
        ),
    ]
