# Generated by Django 5.0.7 on 2024-07-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_snippet_priv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='priv',
        ),
        migrations.AddField(
            model_name='snippet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
